[package]
name = "turborand"
version = "0.1.0"
edition = "2021"
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
description = "A simple and fast random number generator"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Bluefinger/turborand"
keywords = ["fast", "rand", "random", "wyrand"]
categories = ["algorithms"]
exclude = ["/.*"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = "0.1"
