[package]
name = "turborand"
version = "0.2.0"
edition = "2021"
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
description = "A simple and fast random number generator"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Bluefinger/turborand"
keywords = ["fast", "rand", "random", "wyrand"]
categories = ["algorithms"]
exclude = ["/.*"]
resolver = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = "0.1"

[features]
atomic = []

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
