[package]
name = "turborand"
version = "0.5.1"
edition = "2021"
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
description = "A simple and fast random number generator"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Bluefinger/turborand"
keywords = ["fast", "rand", "random", "wyrand"]
categories = ["algorithms"]
exclude = ["/.*"]
resolver = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = "0.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
instant = { version = "0.1", features = [ "wasm-bindgen" ] }
wasm-bindgen-test = "0.3"

[dependencies]
rand_core = { version = "0.6", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3"
serde_json = "1.0"

[[bench]]
name = "rand_bench"
harness = false

[features]
atomic = []
rand = ["dep:rand_core"]
serialize = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
rustc-args = ["--cfg", "docsrs"]
